language: python
cache: pip
sudo: false

python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install --upgrade . .[conventions,docs,tests]

script:
  - flake8
  - pydocstyle aniffinity
  - sphinx-build -W docs/ /tmp/build

deploy:
  provider: pypi
  user: erkghlerngm44
  distributions: sdist bdist_wheel --universal
  on:
    tags: true
    python: 3.6

notifications:
  webhooks:
    urls: https://erkghlerngm44-travis-webhook.herokuapp.com/discord
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
