language: python
cache: pip
sudo: false

python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install --upgrade . .[conventions,docs,tests]

script:
  - flake8
  - pydocstyle aniffinity
  - sphinx-build -W docs/ /tmp/build

deploy:
  provider: pypi
  user: erkghlerngm44
  password:
    secure: KkM8lffzhGG4eFORjqwHXdhunPZhgYVittsc4xz7M65tr9yPGMySycR0wWyj2SKTGsYN6bbPUVasKMRpHsy41UBbJ3zsY2vJAIIsKg5Mn7e523dTIHLKVH+j7vAmJLcu14koDakIRVrm2ZWldMO4rqsJj+UQr/gFI4nMbV7Az5OTO4K2RYtV1w5U+OksRnXuZrWuXKM/FzYFBQ5f38uIcYEJ580x/lxKuOvizZax4MVgG96U4ovRS14QsVfZSom3X2ppcq/+e/FQb9ORXcW83XXZXHlEfS0wi0chweLW2cBZzC2atNxzsMUaiaCOBiAIBkqbVh7+dZcNx3AiIRjdPv8M7c0pMnveY6YYjPnMJanNcJPgT219qTzY064fCiYzt2t+MK1IB5vG5wUzYnVT7061NnJhmg3X4PBEuTHRcHOMYqD7GcrNA+e7cXZH/PCJ5EaCXgIcxAxN3GTgTotNqDTnnkl38q91iZNwEYQKnr6dkeT1b3pd2pVxQbfBvU1vjuKwF8vdNzhbDLfeZlqUclAIpOYwEaNo2Ux8iBqwagk+D3tmjeNzS3oKBuVoho6TaS/0x8rnxvjiCc7aYfIrgxPm2dL+7pxVkql03ViGEse7hp7qVUUrJpVcd7LF1tq74bY17rYwueKKC0Ln0NLL09oabV6XEPnPTSjnQW4dQv4=
  distributions: sdist bdist_wheel --universal
  on:
    tags: true
    python: 3.6

notifications:
  webhooks:
    urls: https://erkghlerngm44-travis-webhook.herokuapp.com/discord
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
